version: "3"
services:
  mongo:
    image: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - reactionsnet
  app:
    image: server/reactions
    ports:
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - reactionsnet

networks:
  reactionsnet:
volumes:
  mongodb_data_container: