---
  networks:
    reactionsnet: ~
  version: "3.2"
  volumes:
    mongo:
  services:
    mongodb:
      image: mongo:3.6
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGODB_USER="bons"
        - MONGODB_PASS="123"
      volumes:
        - 'mongo:/data/db'
      ports:
        - '27017:27017'
      networks:
        - reactionsnet
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: '0.4'
            memory: 250M
        restart_policy:
          condition: on-failure
      healthcheck:
        disable: true